package GoogleCloudProject.GoogleCloudProject;

public class CampaignMessage {

	public static String getMessage(String _activityId, String _id, String id) {
	 String message ="{\r\n"
	 		+ "    \"_activityId\": " + "\"" + _activityId +  "\"" + ",\r\n"
	 		+ "    \"_id\": "+  "\"" + _id +  "\"" +",\r\n"
	 		+ "    \"_version\": 1,\r\n"
	 		+ "  \"resource\": {\r\n"
	 		+ "    \"id\": "+ "\"" + id +  "\"" +",\r\n"
	 		+ "    \"version\": 1,\r\n"
	 		+ "   \"aMCampaignId\":\"20211109161516132489005\",\r\n"
	 		+ "   \"aMCampaignName\":\"Puneet_JanuaryTest\",\r\n"
	 		+ "   \"oEMBulletinNumber\":\"A21UACB1\",\r\n"
	 		+ "   \"oEMBulletinName\":\"Experiential Marketing Incentive Program\",\r\n"
	 		+ "   \"approvalDate\":\"11/1/21\",\r\n"
	 		+ "   \"approverName\":\"Tim\",\r\n"
	 		+ "   \"brand\":\"AUDI\",\r\n"
	 		+ "   \"brandId\":\"AU\",\r\n"
	 		+ "   \"dealerName\":\"Audi Chantilly\",\r\n"
	 		+ "   \"dealerId\":\"AU0098\",\r\n"
	 		+ "   \"customerNumber\":\"241199\",\r\n"
	 		+ "   \"vin\":\"5N1BA0NF5FN605092\",\r\n"
	 		+ "   \"offeramModels\":\"R8\",\r\n"
	 		+ "   \"offerModelCodes\":\"4S35BE,8K251A\",\r\n"
	 		+ "   \"offerAmVehicleIdTrim\":\"A4 Sedan Premium 40 TFSI\",\r\n"
	 		+ "   \"offerAmVehicleId\":\"08D7F523-B8D0-03DC-F69C-FC0001000008\",\r\n"
	 		+ "   \"offerChromeId\":\"411851\",\r\n"
	 		+ "   \"offerModelYear\":\"2020\",\r\n"
	 		+ "   \"offerIncentiveAmount\":\"1000\",\r\n"
	 		+ "   \"startDate\":\"01/06/22\",\r\n"
	 		+ "   \"endDate\":\"03/30/22\",\r\n"
	 		+ "   \"exclusionModels\":\"R7\",\r\n"
	 		+ "   \"exclusionModelCodes\":\"8W254B,8UG5CP\",\r\n"
	 		+ "   \"exclusionModelYears\":\"2020,2019\",\r\n"
	 		+ "   \"eligibleDealTypes\":\"ALL\",\r\n"
	 		+ "   \"altIncentiveAmount\":\"300.0\",\r\n"
	 		+ "   \"redemptionCode\":\"07BC4341\",\r\n"
	 		+ "   \"currentAmVehicleId\":\"08D67B3B-3FD3-38FD-6217-680001000110\",\r\n"
	 		+ "   \"closedDealId\":\"6ADB18C0-188A-4486-9BC1-0032EB71DA16\",\r\n"
	 		+ "   \"chromeId\":\"402843\"\r\n"
	 		+ "  },\r\n"
	 		+ "  \"_origin\": {\r\n"
	 		+ "    \"name\": \"am.private.incentives\",\r\n"
	 		+ "    \"version\": \"2.0.0\",\r\n"
	 		+ "    \"namespace\": \"stg\",\r\n"
	 		+ "    \"node\": \"nodenameasastring\",\r\n"
	 		+ "    \"pod\": \"feb8734\",\r\n"
	 		+ "    \"container\": \"containernameasastring\"\r\n"
	 		+ "    },\r\n"
	 		+ " \"_timestamp\": 1536616434\r\n"
	 		+ "}";
	 return message;
	}
}
